### PR TITLE
Fix Tests

### PR DESCRIPTION
**Pull request by maennchen**
Fix for #44

### CODE REVIEW

**Comment by bryanhuntesl** [comment]
This is still breaking on my machine - I've submitted a separate #46 to create a Travis config - it might help to document failed tests.

```
▷ mix test 
                                        
                     
  1) test disconnect_nodes/4 handles disconnect ignore (Cluster.StrategyTest)        
     test/strategy_test.exs:97                                                   
     ** (RuntimeError) Elixir.Cluster.Nodes.list_nodes/1 is undefined!                                                   
     code: assert capture_log(fn ->                                            
     stacktrace:                                                      
       (libcluster) lib/strategy/strategy.ex:117: Cluster.Strategy.ensure_exported!/3
       (libcluster) lib/strategy/strategy.ex:80: Cluster.Strategy.disconnect_nodes/4
       test/strategy_test.exs:103: anonymous fn/1 in Cluster.StrategyTest."test disconnect_nodes/4 handles disconnect ignore"/1
       (ex_unit) lib/ex_unit/capture_log.ex:78: ExUnit.CaptureLog.capture_log/2
       test/strategy_test.exs:101: (test)
```

**Comment by maennchen** [comment]
@bryanhuntesl I have no idea why that module is not always available. If I open & save without changes, the tests pass once and then the module is missing again.

**Comment by bryanhuntesl** [comment]
Weird - what are you using to code? Could it be something that is only in your local environment ?

**Comment by bitwalker** [comment]
I've already fixed these tests on another branch (including the weird module missing thing). I'm going to close this for now, but thanks for submitting this, it is definitely appreciated :)

**Pull request closed without merging**
