### PR TITLE
Add an option to activate/deactivate warn messages

### PR DESCRIPTION
**Pull request by Fibrasek**
### Summary of changes

Adds a config option to deactivate `warn` messages, so it don't spam those messages in cases with a lot of known nodes that can't be connected to, for example: different applications with different release cookies in the same network, using DNSPoll strategy.

### CODE REVIEW

**Review by bitwalker — CHANGES_REQUESTED** [review]
It feels a bit odd to control only debug and warning messages here. If you simply want to disable logs up to a specific log level just from `libcluster`, you can do that via Logger's configuration without requiring any change in `libcluster` itself. I was thinking that it might be a better change to instead remove/modify the nosiy logging going on in the adapter that was spamming your system, since it's clearly not an appropriate warning to be generating.

**Comment by Fibrasek** [comment]
To be honest, idk if the `Logger` can be configured to be selective about what modules to suppress or set their log level at runtime. Do you know if that's possible? If so, this PR will be useless xD

**Comment by bitwalker** [comment]
You can indeed! To specifically filter logs of level `:warn` and below from the `:libcluster` logger, you can use the following:

```elixir
config :logger,
  backends: [:console],
  compile_time_purge_matching: [
    [module: Cluster.Logger, level_lower_than: :error]
  ]
```

If you just want to disable all `:libcluster` logs, you can replace the keyword list with `[application: :libcluster]`.

NOTE: You must recompile libcluster for this change to take effect, I think it should be sufficient to run `mix deps.compile --force libcluster`, but if that doesn't do it, you can just blow away your `_build` folder and recompile everything.

**Comment by Fibrasek** [comment]
So if that's possible, the PR don't make sense. It'll would be cool to have note on the documentation on how to do that :)

**Pull request closed without merging**
